### ISSUE TITLE
修正

### ISSUE THREAD

**Issue by quojama** [pistachiostudio/valorant_map#2]
- Plant pointが一部おかしいところがあるらしい(茂林に確認)
- 改めて名称を精査

**Comment by stillmitsushige** [comment]
@quojama 
> Plant pointが一部おかしいところがあるらしい(茂林に確認)

どこでしょうか

**Comment by quojama** [comment]
@stillmitsushige いや自分がおかしいとこあるって言ってたから逆に聞きたいんだけど
